export enum SettingsDialogState {
  NONE = 'NONE',
  CHANGE_EMAIL = 'CHANGE_EMAIL',
  CONFIRM_CHANGE_EMAIL = 'CONFIRM_CHANGE_EMAIL',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS',
}
